export type MeetingPlan = {
  number: number
  title: string
  resources: string[]
  foundations: string[]
  curriculum: string[]
  challenges: string[]
}

export const MEETING_PLANS: MeetingPlan[] = [
  {
    number: 0,
    title: 'Onboarding',
    resources: [],
    foundations: [],
    curriculum: [
      'Leadership introduce themselves, then each member introduces themselves',
      'Why did you join BT?',
      'If members have a preference on table meeting times, let us know',
      'Overview of Sunrise Network and logistics — Mo gives tutorial',
      'Events & Groups — this is where our group will communicate',
      'A new group will be created just for your table with your TC',
      'Coworking space — welcome to use it any time',
    ],
    challenges: [
      'BT Structure: Values, purpose, vision, goals, paradigms, practices and next steps',
      'Introduce the playbook',
      'Introduce the accountability tracker',
      'Introduce awareness journaling',
      'Introduce the goal card',
      'Set up Sunrise Network profile',
    ],
  },
  {
    number: 1,
    title: 'Self Awareness',
    resources: [
      'The Five Laws of Stratospheric Success handout',
      'Chapter 2 from As a Man Thinketh: Effect of Thought on Circumstance',
      'Infinite Possibilities by Mike Dooley handout',
      'Mel Robbins video — No One Is Coming (:55)',
      'Strangest Secret by Earl Nightingale',
      'Peter Crone video — The One Thing That Is Limiting Your Progress (4:52)',
    ],
    foundations: [
      'Go Giver takeaways',
      '5 stratospheric laws of success — tied to a goal',
      'Awareness journaling',
      'Your goal — you\'re here because you want something. What is your goal?',
    ],
    curriculum: [
      'Performance and 100% responsibility — Page 1 of playbook',
      'Importance of taking control of your thoughts/thinking',
      'If this is new to you, learn how to RELAX your mind and body periodically',
      'Slow down your thought stream so you can observe your thoughts',
      'Feelings drive thoughts and thoughts drive feelings',
      'Monitor your FEELINGS just as much as your THOUGHTS',
      'Neuroscience resource about thinking',
      'Teachability index',
      'Goal cards',
    ],
    challenges: [
      'Begin Practicing Awareness Journaling 3x DAILY',
      'Think about the first Stratospheric Law of Success and how it applies to you daily',
      'What resistance are you feeling as you journal?',
      'Read Chapter 2 from As a Man Thinketh: Effect of Thought on Circumstance',
      'Listen to Strangest Secret by Earl Nightingale',
      'Peter Crone video — The One Thing That Is Limiting Your Progress: https://www.youtube.com/watch?v=ZBF2PvjqcJE',
      'Mel Robbins video: https://thesunrisenetwork.com/resources/86284/mel-robbins-the-hard-truth-about-making-your-dreams-come-true',
      'Fill out your Goal card after listening to the resources',
    ],
  },
  {
    number: 2,
    title: 'Values',
    resources: [
      'Values Determining Questions handout',
      'Science of Getting Rich — Chapter 12 handout',
      'Demartini video #1 — What are your highest values? (0:48)',
    ],
    foundations: [
      'Awareness Journaling — how is it going, any resistance?',
      'Earl Nightingale compare/contrast to John\'s video — thoughts and resistance',
      'Goal card check-in',
      'Any other thoughts from the videos and handouts',
      'Page 2 in playbook',
    ],
    curriculum: [
      'Values questions',
      'Identifying your top 3 values through the values questions',
      'DeMartini exercise discussion',
      'Complete question 3 in Purpose section of Playbook',
    ],
    challenges: [
      'Continue awareness journal 3X DAILY',
      'Answer values questions DAILY — see how your answers shift and change',
      'Watch DeMartini video #2 — How To Determine Your Core Values | 13 Questions',
      'Read Science of Getting Rich — Chapter 12',
    ],
  },
  {
    number: 3,
    title: 'Purpose',
    resources: [
      'Read Grit chapter 3 and 8 — Optional',
      'Best Self by Coach Mike Bayer — Optional',
      'Jack Canfield Video — 3 Tips to Find Your Life Purpose (7:56): https://www.youtube.com/watch?v=mwRH7QdFbjs',
      'Brene Brown — It\'s Not The Critic Who Counts (5:19): https://www.youtube.com/watch?v=VPyaBmPr_qM',
      'Napoleon Hill — Law of Success in 16 Lessons (5:19): https://www.youtube.com/watch?v=MLyjcCKTzfc',
      'Marcus Aurelius — Find Your Purpose: Stoic Philosophy (6:58): https://www.youtube.com/watch?v=S9e1VVtFXmQ',
      'Andrew Huberman — NEUROSCIENTIST: Become MOTIVATED in ANYTHING you do (7:01): https://www.youtube.com/watch?v=xqLxyETmlWo',
    ],
    foundations: [
      'Awareness journaling check-in',
      'Values check-in — what did you discover?',
      'How do your values connect to your goal?',
    ],
    curriculum: [
      'What is your purpose?',
      'How does purpose differ from a goal?',
      'Purpose statement exercise',
      'Who benefits the most from you finding/achieving your purpose?',
      'Pages 3-4 in playbook — Purpose section',
    ],
    challenges: [
      'Continue awareness journal 3X DAILY',
      'Draft your purpose statement',
      'Watch the Jack Canfield and Andrew Huberman videos',
      'Answer purpose questions in the playbook',
    ],
  },
  {
    number: 4,
    title: 'Vision (Part 1)',
    resources: [],
    foundations: [
      'Share Awareness Journal takeaways',
      'Share Takeaways from Science of Getting Rich — Chapter 12',
      'Importance of being committed, showing up, mastermind group',
      'Define mastermind for this group — all share core values',
    ],
    curriculum: [
      'Question 3 in purpose section',
      'Review pages 2-4 from Purpose section of Playbook',
      'Answer questions 1-2 in purpose section',
      'Writing your purpose statement',
      'What was the experience like while crafting your purpose statement draft?',
      'Who benefits the most from you achieving/finding your purpose?',
      'How did you get to this purpose statement?',
      'Introduce vision section of playbook',
      'How do you want to live in all areas of life?',
    ],
    challenges: [
      'Continue awareness journal 3X DAILY',
      'Finalize purpose statement draft',
      'Begin thinking about your vision — how do you want to live?',
      'Read vision section of playbook',
    ],
  },
  {
    number: 5,
    title: 'Vision (Part 2)',
    resources: [
      'Gratitude handout by Lee Coit from Louise Hay book',
      '8 Habits of Curious People handout',
      'Imagination Exercise handout',
      'Excerpt from Success Principles: Chapter 3 — Decide What You Want',
      'Gratitude — Louie Schwartzberg video',
      'Curiosity Is Your Super Power | Spencer Harrison & Jon Cohen (17:28)',
      'Develop Your Imagination (7:00) — Bob Proctor',
      'Expand Your Imagination Ted Talk — Jeff Bollow (15:37)',
    ],
    foundations: [
      'Awareness journaling check-in',
      'Purpose statement share',
      'Importance of Gratitude',
    ],
    curriculum: [
      'Imagination — what does it mean to you?',
      'How do you exercise your imagination?',
      'Do you feel your imagination can be strengthened?',
      'How do some people misuse their imagination unconsciously?',
      'How can we learn to consciously exercise our imagination?',
      'Gratitude practice exercise',
      'Perfect Day exercise — write out your perfect day in detail',
    ],
    challenges: [
      'Continue awareness journal 3X DAILY',
      'Complete the Perfect Day exercise',
      'Watch the Bob Proctor and Curiosity videos',
      'Practice daily gratitude',
    ],
  },
  {
    number: 6,
    title: 'Vision (Part 3)',
    resources: [
      'Excerpt from The Slight Edge about wanting/desire',
      'Vision Statement Examples handout',
      'Clark Kegley — How to Make a Vision Board (21:33)',
      'Brian Tracy — The Power of Clear Vision (21:06)',
    ],
    foundations: [
      'Awareness Journal check-in — reiterate importance of continuing to journal',
      'Thoughts on excerpt from Jack Canfield\'s Success Principles: Chapter 3',
      'How did it go writing out your perfect day — share one aspect',
      'What type of emotions does this bring up?',
      'How does your perfect day relate to your values and purpose?',
    ],
    curriculum: [
      'What do YOU want? Is it what you think you "should" want?',
      'Vision statement — what does yours look like?',
      'Vision board — how to create one',
      'Watch Clark Kegley video as a group',
      'What type of vision board resonates with you?',
    ],
    challenges: [
      'Continue awareness journal 3X DAILY',
      'Draft your vision statement',
      'Create a vision board (physical or digital)',
      'Watch Brian Tracy — The Power of Clear Vision',
    ],
  },
  {
    number: 7,
    title: 'Goals & Resistance',
    resources: [
      'Chapter 10 from Napoleon Hill\'s Secret',
      'Excerpt from Canfield Success Principles — Chapter 7: Unleash the Power of Goalsetting',
      'The Rocket drawing and breakdown handout',
      'Mel Robbins video (10:02) — The Number 1 Habit Billionaires Run Daily',
      'Jim Rohn video — Reasons Come First, Answers Come Second (9:14)',
      'DeMartini Short — Link Your Goals to What\'s Valuable',
      'Jack Canfield — How to Follow Through on Your Goals (6:23)',
    ],
    foundations: [
      'Awareness journaling check-in',
      'Share drafts of vision statement and vision board',
      'Have a member share an example of how having these is directly causing them to take action',
      'Share Perfect Day Exercise with the group',
      'Any other vision takeaways from the resources?',
    ],
    curriculum: [
      'Intro to Goals section',
      'SMART goals framework',
      'Connecting goals to your vision, purpose, and values',
      'What resistance do you feel when thinking about your goals?',
      'Identifying the "rocket" — what\'s propelling you and what\'s holding you back?',
    ],
    challenges: [
      'Continue awareness journal 3X DAILY',
      'Write out 3-5 SMART goals',
      'Watch Mel Robbins and Jim Rohn videos',
      'Identify your biggest source of resistance to your #1 goal',
    ],
  },
  {
    number: 8,
    title: 'Goals & Paradigms',
    resources: [
      'Chapter 11: Key Characteristics of Paradigms — Joel Arthur Barker',
      'Step 1: Paradigm Assessment Rating Exercise handout',
      'Step 2: Paradigm Breaker (3Rs) handout',
      'Limiting Beliefs handout',
      'Paradigm Breaker — 3 R\'s Columns exercise',
      'Excerpt from Chapter 1 of Switch on Your Brain — Dr. Caroline Leaf',
      'Step 3: Anything is Possible — Paradigm Ceiling graphic handout',
      'Step 4: Challenging negative beliefs handout',
      'The Compound Effect — Chapter 4: Momentum',
      'Jack Canfield — How to Follow Through on Your Goals (6:23)',
      'Paradigms video from Franklin Covey (3:47)',
    ],
    foundations: [
      'Awareness journaling check-in',
      'Goal sharing — how is the goal-setting going?',
      'What resistance came up?',
      'Vision and purpose connection check-in',
    ],
    curriculum: [
      'What is a paradigm?',
      'How paradigms affect your goals and results',
      'Paradigm Assessment — where are you right now?',
      'Paradigm Breaker — the 3 R\'s: Recognize, Reframe, Replace',
      'Limiting beliefs vs. empowering beliefs',
      'The Paradigm Ceiling — what\'s your ceiling?',
      'Compound effect — how small actions build momentum',
    ],
    challenges: [
      'Continue awareness journal 3X DAILY',
      'Complete Paradigm Assessment',
      'Do the Paradigm Breaker exercise for your #1 limiting belief',
      'Read The Compound Effect — Chapter 4',
      'Watch Franklin Covey Paradigms video',
    ],
  },
  {
    number: 9,
    title: 'Paradigms & Goals',
    resources: [
      'The Sedona Method — Dissolving Your Resistance, Chapter 4 excerpt',
      '3 Mental Habits of the Highly Successful — Andrew Huberman (7:04)',
      'James Clear video — 10 minutes to start your day right!',
    ],
    foundations: [
      'Awareness journaling check-in',
      'Paradigm assessment and breaker handouts experience — results and resistance',
      'What limiting beliefs came up?',
    ],
    curriculum: [
      'Towards the achievement of your BT goal — be observant around feelings of resistance',
      'Write resistance down as part of awareness journaling practice',
      'Be aware of limiting beliefs that come about with feelings of resistance',
      'When possible: state the limiting belief and actively reframe',
      'Read Chapter 4 from the Sedona Method — Dissolving Your Resistance',
      'The letting go technique',
    ],
    challenges: [
      'Continue awareness journal 3X DAILY',
      'Read Sedona Method Chapter 4',
      'Watch Andrew Huberman and James Clear videos',
      'Practice the letting go technique daily',
      'Notice and write down every moment of resistance this week',
    ],
  },
  {
    number: 10,
    title: 'Paradigms (Continued)',
    resources: [],
    foundations: [
      'Awareness journaling check-in',
      'Are you noticing any results?',
      'What have been your key takeaways the past 2 weeks?',
    ],
    curriculum: [
      'Continue having each member share their goal, paradigms around that, and action steps',
      'Review Breakthrough Challenges',
      'Continue awareness journaling',
      'Accountability check — who has been doing the work?',
    ],
    challenges: [
      'Continue awareness journaling daily',
      'Continue working on paradigm breakers',
      'Report back on goal progress',
    ],
  },
  {
    number: 11,
    title: 'Practices',
    resources: [],
    foundations: [
      'Awareness journaling check-in',
      'Paradigm breaker handouts — if applicable',
      'Goal check-ins',
    ],
    curriculum: [
      'Practices — this is where we start taking action by creating your own daily routine',
      'What resistance did you feel when reading through pages 34 and 35?',
      'Resistance is an indicator that something is blocking your path',
      'Resistance typically stems from a limiting belief/paradigm',
      'We must be willing to challenge the resistance or feeling of fear',
      'Are these 10 habits a luxury or a choice? (Hint: it is a choice!)',
      'Science behind checking off items on your daily routine',
      'How do your values tie to your daily routine?',
      '10 habits in playbook',
      'Continue reinforcement of mastermind',
    ],
    challenges: [
      'Continue awareness journaling daily',
      'Begin building your daily routine around the 10 habits',
      'Track your habits in the accountability tracker',
      'Identify which habits feel most natural and which create resistance',
    ],
  },
  {
    number: 12,
    title: 'Practices (Continued)',
    resources: [],
    foundations: [
      'Awareness journaling check-in',
    ],
    curriculum: [
      'Practices — continue taking action by building your daily routine',
      'Check in on goal and new habits',
      'Congrats on finishing the playbook!',
      'How has your thinking changed since Meeting #1?',
      'What results are you seeing?',
    ],
    challenges: [
      'Continue awareness journaling daily',
      'Continue implementing new habits',
      'Outline options for continued membership',
      'Next steps for your BT journey',
    ],
  },
]
